repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-ast
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: ['--py38-plus']

#-    repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.910-1
#     hooks:
#     -   id: mypy
#         exclude: ^ref_repos/
#         args: [--ignore-missing-imports]
#         additional_dependencies: [types-PyYAML, types-requests, types-PyMySQL]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
        args: [-e]
